name: waslny_pusher_test_driver
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  get_it: ^7.2.0
  dio: ^4.0.6
  pusher_channels_flutter: ^2.5.0
  google_maps_flutter: ^2.12.1
  cupertino_icons: ^1.0.2
  awesome_notifications_core: ^0.10.1 # use the latest core version available
  awesome_notifications: ^0.10.1 # This version is managed by core plugin
  flutter_background_service: ^5.1.0
  logger: ^2.6.0
  permission_handler: ^11.3.1
  internet_connection_checker_plus: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
