// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzdaE6altf3kimktHOlIqnGdh9nQexcw',
    appId: '1:1001820982794:web:6e436c50cf3e829c5a59f3',
    messagingSenderId: '1001820982794',
    projectId: 'note-app-61388',
    authDomain: 'note-app-61388.firebaseapp.com',
    storageBucket: 'note-app-61388.firebasestorage.app',
    measurementId: 'G-2JX02VGLK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTA9rFZtggB5_SZmRxytJbPZ0YgguMuu8',
    appId: '1:1001820982794:android:2751ceb43065e0465a59f3',
    messagingSenderId: '1001820982794',
    projectId: 'note-app-61388',
    storageBucket: 'note-app-61388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYznOwvv0OW2cRArX39Mj6W0GiYHnM5XI',
    appId: '1:1001820982794:ios:a5f0ff78f4b35a735a59f3',
    messagingSenderId: '1001820982794',
    projectId: 'note-app-61388',
    storageBucket: 'note-app-61388.firebasestorage.app',
    iosBundleId: 'com.example.waslnyPusherTestDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYznOwvv0OW2cRArX39Mj6W0GiYHnM5XI',
    appId: '1:1001820982794:ios:a5f0ff78f4b35a735a59f3',
    messagingSenderId: '1001820982794',
    projectId: 'note-app-61388',
    storageBucket: 'note-app-61388.firebasestorage.app',
    iosBundleId: 'com.example.waslnyPusherTestDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM04OUzip5nYczFiyA_4H90JwSLOOAD3I',
    appId: '1:1001820982794:web:0c015e803c64c6a65a59f3',
    messagingSenderId: '1001820982794',
    projectId: 'note-app-61388',
    authDomain: 'note-app-61388.firebaseapp.com',
    storageBucket: 'note-app-61388.firebasestorage.app',
    measurementId: 'G-5SQQF55E1K',
  );
}
